### PR TITLE
Add support for non-namespaced resource kinds

### PR DESCRIPTION
**Pull request by ibazhitov**

### CODE REVIEW

**Comment by ibazhitov** [comment]
Bump to verify CLA

**Comment by pwittrock** [comment]
Thanks for the PR!  This is something I have been meaning to add.  Since it is a bit longer, it is going to take me a little while to look through it.  Will look in detail tomorrow.

**Comment by pwittrock** [comment]
Would you add a new xxx_types.go to the example and a test so this logic is not broken in the future?

**Comment by ibazhitov** [comment]
> Would you add a new xxx_types.go to the example and a test so this logic is not broken in the future? It will also demonstrate how to use the feature.

OK. I'm going to split this PR into three, since it includes bug fixes that are not essential to the main 'non-namespaced resource' feature.

**Comment by ibazhitov** [comment]
Closing this in favor of #66, #67 and #68

**Comment by pwittrock** [comment]
Thank you, that would be easier.  I can merge the bug fixes quickly.

**Pull request closed without merging**
