### PR TITLE
Adding Contributing Guideline

### PR DESCRIPTION
**Pull request by RA489**

### CODE REVIEW

**Comment by nikhita** [comment]
@RA489 Thanks for submitting the pull request! The contributing guidelines need to be as per https://github.com/kubernetes/kubernetes-template-project. Closing in favor of #259.

/close

**Comment by warmchang** [comment]
/close by https://github.com/kubernetes-incubator/apiserver-builder/pull/257#issuecomment-417859938
cc @nikhita

**Comment by nikhita** [comment]
@warmchang Thank you!

**Comment by warmchang** [comment]
Welcome! @nikhita

**Pull request closed without merging**
